// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SessionEventType string

const (
	SessionEventTypeStart  SessionEventType = "start"
	SessionEventTypePause  SessionEventType = "pause"
	SessionEventTypeResume SessionEventType = "resume"
	SessionEventTypeStop   SessionEventType = "stop"
)

func (e *SessionEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionEventType(s)
	case string:
		*e = SessionEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionEventType: %T", src)
	}
	return nil
}

type NullSessionEventType struct {
	SessionEventType SessionEventType `json:"session_event_type"`
	Valid            bool             `json:"valid"` // Valid is true if SessionEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionEventType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionEventType), nil
}

type Project struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Name               string             `json:"name"`
	MonthlyTargetHours pgtype.Numeric     `json:"monthly_target_hours"`
	Archived           bool               `json:"archived"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	ProjectID int64              `json:"project_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SessionEvent struct {
	ID         int64              `json:"id"`
	SessionID  int64              `json:"session_id"`
	Type       SessionEventType   `json:"type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
