// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, monthly_target_hours)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, monthly_target_hours, archived, created_at
`

type CreateProjectParams struct {
	UserID             int64          `json:"user_id"`
	Name               string         `json:"name"`
	MonthlyTargetHours pgtype.Numeric `json:"monthly_target_hours"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.MonthlyTargetHours)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MonthlyTargetHours,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, project_id, started_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, project_id, started_at, ended_at, created_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	ProjectID int64              `json:"project_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ProjectID, arg.StartedAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSessionEvent = `-- name: CreateSessionEvent :one
INSERT INTO session_events (session_id, type, occurred_at)
VALUES ($1, $2, $3)
RETURNING id, session_id, type, occurred_at
`

type CreateSessionEventParams struct {
	SessionID  int64              `json:"session_id"`
	Type       SessionEventType   `json:"type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRow(ctx, createSessionEvent, arg.SessionID, arg.Type, arg.OccurredAt)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.OccurredAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET ended_at = $3
WHERE id = $1 AND user_id = $2 AND ended_at IS NULL
RETURNING id, user_id, project_id, started_at, ended_at, created_at
`

type EndSessionParams struct {
	ID      int64              `json:"id"`
	UserID  int64              `json:"user_id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.ID, arg.UserID, arg.EndedAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, project_id, started_at, ended_at, created_at
FROM sessions
WHERE user_id = $1 AND ended_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveSession(ctx context.Context, userID int64) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, monthly_target_hours, archived, created_at
FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MonthlyTargetHours,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, project_id, started_at, ended_at, created_at
FROM sessions
WHERE id = $1 AND user_id = $2
`

type GetSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsForSessions = `-- name: ListEventsForSessions :many
SELECT e.id, e.session_id, e.type, e.occurred_at
FROM session_events e
JOIN sessions s ON s.id = e.session_id
WHERE s.user_id = $1
  AND s.started_at >= $2
  AND s.started_at < $3
ORDER BY e.occurred_at ASC
`

type ListEventsForSessionsParams struct {
	UserID      int64              `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

func (q *Queries) ListEventsForSessions(ctx context.Context, arg ListEventsForSessionsParams) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForSessions, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, monthly_target_hours, archived, created_at
FROM projects
WHERE user_id = $1
ORDER BY archived ASC, name ASC
`

func (q *Queries) ListProjects(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MonthlyTargetHours,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, session_id, type, occurred_at
FROM session_events
WHERE session_id = $1
ORDER BY occurred_at ASC
`

func (q *Queries) ListSessionEvents(ctx context.Context, sessionID int64) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.user_id, s.project_id, s.started_at, s.ended_at, s.created_at, p.name AS project_name
FROM sessions s
JOIN projects p ON p.id = s.project_id
WHERE s.user_id = $1
  AND ($2::timestamptz IS NULL OR s.started_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR s.started_at < $3::timestamptz)
  AND ($4::bigint IS NULL OR s.project_id = $4::bigint)
ORDER BY s.started_at DESC
`

type ListSessionsParams struct {
	UserID    int64              `json:"user_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
	ProjectID *int64             `json:"project_id"`
}

type ListSessionsRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	ProjectID   int64              `json:"project_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, monthly_target_hours = $4, archived = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, monthly_target_hours, archived, created_at
`

type UpdateProjectParams struct {
	ID                 int64          `json:"id"`
	UserID             int64          `json:"user_id"`
	Name               string         `json:"name"`
	MonthlyTargetHours pgtype.Numeric `json:"monthly_target_hours"`
	Archived           bool           `json:"archived"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.MonthlyTargetHours,
		arg.Archived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MonthlyTargetHours,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
