// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) (SessionEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	EndSession(ctx context.Context, arg EndSessionParams) (Session, error)
	GetActiveSession(ctx context.Context, userID int64) (Session, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListEventsForSessions(ctx context.Context, arg ListEventsForSessionsParams) ([]SessionEvent, error)
	ListProjects(ctx context.Context, userID int64) ([]Project, error)
	ListSessionEvents(ctx context.Context, sessionID int64) ([]SessionEvent, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
